name: Build

on:
    push:
        branches:
            - master
            - releases/**
        tags:
            - v*

jobs:
    build:
        strategy:
            matrix:
                os: [ windows-latest, ubuntu-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout master
              uses: actions/checkout@master
              with:
                persist-credentials: false
                fetch-depth: 0
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
            - name: Install dependencies
              run: npm install
            - name: Build
              run: |
                npm run build
                npm run test --if-present
            - name: Package
              run: |
                npm run package
